version: "3.3"

services:
  database:
    container_name: cursodjango_database
    image: postgres:11.5
    restart: always
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=t7jiV6g16OMGjbp
      - POSTGRES_USER=postgres
    ports:
      - 5434:5432